/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kci;

import com.kci.command.KciCommand;
import org.junit.jupiter.api.Test;

class KciCommandTest {
    @Test void appHasAGreeting() {
        KciCommand classUnderTest = new KciCommand();
    }
}
